from typing import Protocol, runtime_checkable, Any

from binance import KLINE_INTERVAL_1DAY
from binance.client import Client


@runtime_checkable
class BinanceClientAdapterPort(Protocol):
    def __init__(
            self,
            binance_client: Client,
    ): ...

    def get_open_orders(self) -> list[dict[str, Any]]: ...

    def get_all_orders(self, symbol: str) -> list[dict[str, Any]]: ...

    def get_order_by_binance_order_id(self, binance_order_id: int, binance_order_symbol: str) -> dict[str, Any]: ...

    def get_price_for_binance_symbol(self, binance_order_symbol: str) -> dict[str, Any]: ...

    def get_historical_klines(self, binance_order_symbol: str, period: str, interval: str = KLINE_INTERVAL_1DAY) -> list: ...

    def get_asset_balance(self, asset=None) -> dict[str, Any]: ...

    def get_symbol_info(self, symbol: str) -> dict[str, Any]: ...

    def create_test_order(self, **params) -> dict: ...

    def create_order(self, **params) -> dict: ...