SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE balances;
TRUNCATE TABLE cron_jobs;
TRUNCATE TABLE order_trades;
TRUNCATE TABLE orders;
TRUNCATE TABLE orders_filling_history;
TRUNCATE TABLE settings;
SET FOREIGN_KEY_CHECKS=1;
